# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 686606b42a24b10bfc6440348b54f0fe9ad7804b5d4ed97649b8d517444da7aa2dbb458b4a432451c87fea607bf310fe35e8784fe785aebce31899022f1784ab

test:
  secret_key_base: c61d86e11925966a19ea116c24d5b4d350c3564602ce2598afc9554344ad9fe476091434782d3400d5f8be29f596d3010118a1f9d666d60f9a9587eba6599e57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
